name: darwin_file_indexer_results
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  syncfusion_flutter_charts: ^21.1.39
  window_manager: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
