name: darwin_file_indexer_results
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.1
  window_manager: ^0.3.2
  dartssh2: ^2.8.2
  logger: ^1.3.0
  syncfusion_flutter_charts: ^21.1.39
  provider: ^6.0.5
  path_provider: ^2.0.15
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dfi
